name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress.io
        uses: cypress-io/github-action@v4.0.0
        with: 
          browser: chrome
      - name: Report Status
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          notify_when: 'success'
          channel : '#random'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
      - name: Upload screenshots
        uses: actions/upload-artifact@latest
        if: failure()
        with:
                name: cypress-snapshots
                path: cypress/snapshots
      - name: "Upload screenshots to Slack"
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
         token: ${{ secrets.SLACK_TOKEN }}
         channels: "#random"
         message-text: "Cypress tests failed! They have been placed in this thread, good luck."
