name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress.io
        uses: cypress-io/github-action@v4.0.0
        with: 
          browser: chrome
          record: true
        env:
            # pass the Dashboard record key as an environment variable
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            # pass GitHub token to allow accurately detecting a build vs a re-run build
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Notification Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: random
          SLACK_TITLE: Update
          SLACK_USERNAME: BotCI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "<https://dashboard.cypress.io/projects/n49r7v/runs?branches=%5B%5D&committers=%5B%5D&flaky=%5B%5D&page=1&status=%5B%5D&tags=%5B%5D&timeRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D|Click here> for more details."
