name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress.io
        uses: cypress-io/github-action@v4.0.0
        with: 
          browser: chrome
          record: true
        env:
            # pass the Dashboard record key as an environment variable
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            # pass GitHub token to allow accurately detecting a build vs a re-run build
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  messageSlack:
    runs-on: ubuntu-latest
    steps:      
      - name: Notification Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: random
          
          SLACK_USERNAME: BotCI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "<https://dashboard.cypress.io/projects/n49r7v/runs|Click here> for more details."
