name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress.io
        uses: cypress-io/github-action@v4.0.0
        with: 
          browser: chrome
          record: true
        env:
            # pass the Dashboard record key as an environment variable
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            # pass GitHub token to allow accurately detecting a build vs a re-run build
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: 'engineering-ops'
          message-text: 'Cypress tests failed! They have been placed in this thread, good luck.'
